name: Post PR Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  terraform_destory:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./Infra/AppService
    env:
      TF_KEY: 'pr-${{ github.event.number }}.tfstate'
      TF_VAR_environment: 'pr-${{ github.event.number }}'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: "Terraform Init"
        id: init
        run: terraform init --backend-config="key=$TF_KEY"

      - name: "Terraform Destroy"
        run: terraform destroy -auto-approve

      